### ISSUE TITLE
Binary number ordering wrong?

### ISSUE THREAD

**Issue by luteberget** [koengit/satplus#5]
The `Binary` type's `Order` instance seems to do lexicographical comparison on the list of digits, but this list is stored with least significant bit first. I think that just reversing the bits gives the correct constraints.

The following seems to do the trick:
```haskell
instance Order Binary where
  lessOr s pre b (Binary xsLSBF) (Binary ysLSBF) =
    do lessOr s pre b xs ys
    where xs = reverse (pad xsLSBF ysLSBF)
          ys = reverse (pad ysLSBF xsLSBF)
```

Is `Binary` worth using for some things, or can one always use `Term` instead?

Test program:
```haskell
module Main where
import SAT
import SAT.Order
import SAT.Binary

main = do
  withNewSolver $ \s -> do
    a <- newBinary s 16
    greaterThan s a (number 5000)
    b <- solve s []
    if b then do
      v <- SAT.Binary.modelValue s a
      putStrLn (show v)
    else error "unsat"
```
Outputs: `2`.

**Comment by koengit** [comment]
Oops, I think you are right.

Binary can be used more efficiently than Term if you optimize over it. Or
if you do a lot of computation and want to reuse the intermediate results
(before you use them in a comparison).

/Koen

**Comment by koengit** [comment]
Would you submit a pull request? Otherwise, I can just fix it. /Koen
